---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: run-test-suite-from-image
spec:
  description: >-
    Run-testsuite-from-image base pipeline runs a specific testsuite from
    a base image containing the software with the specific test suites.
    The pipeline will abstract the OCP cluster specifics so that it is able to
    run on multiple sites and in any cluster modality
    (e.g., SNO or three-compact cluster node).
  params:
    - name: TESTS_IMAGE
      type: string
      description: |
        The image used to run the tests. This can be a base image,
        or an image that already has pre-requirements installed.
      # yamllint enable rule:line-length
    - name: FEATURE
      default: "sriov"
      description: |
        Feature in managed cluster under test.
        Allowed values are "sriov" (tested) and "ptp" (untested).
    - name: CLUSTER_NAME
      description: |
        Name of the managed cluster
    - name: NAMESPACE
      description: |
        Namespace of managed cluster in the hub cluster.
    - name: NOTIF_URL
      description: |
        Google chat webhook URL to send MESSAGE.
    - name: MESSAGE
      description: |
        Message to send.
    - name: WORKER1
      description: |
        Compact cluster worker 1 name under test.
    - name: WORKER2
      description: |
        Worker 2 name under test.
    - name: INTERFACES
      description: |
        Two interface ports present in WORKER1,
        connected to equivalent interface ports in WORKER2.
  tasks:
    - name: send-notification
      taskRef:
        name: send-to-gchat-space
        kind: Task
      params:
        - name: webhook-url
          value: $(params.NOTIF_URL)
        - name: message
          value: "start test suite run from image..."
    - name: get-kubeconfig
      when:
        - input: "$(params.FEATURE)"
          operator: in
          values: ["sriov"]
      taskRef:
        name: get-kubeconfig
        kind: Task
      runAfter:
        - send-notification
      params:
        - name: cluster-name
          value: $(params.CLUSTER_NAME)
      workspaces:
        - name: kubeconfigs
          workspace: pipeline-ws
    - name: run-ptp-suite
      when:
        - input: "$(params.FEATURE)"
          operator: in
          values: ["ptp"]
      taskRef:
        name: deploy-ptp-gotests
        kind: Task
      runAfter:
        - send-notification
    - name: run-sriov-suite
      when:
        - input: "$(params.FEATURE)"
          operator: in
          values: ["sriov"]
      taskRef:
        name: deploy-gotests
        kind: Task
      runAfter:
        - get-kubeconfig
      params:
        - name: IMAGE
          value: $(params.TESTS_IMAGE)
        - name: FEATURE
          value: $(params.FEATURE)
        - name: CLUSTER_NAME
          value: $(params.CLUSTER_NAME)
        - name: NODE1
          value: $(params.WORKER1)
        - name: NODE2
          value: $(params.WORKER2)
        - name: INTERFACE_LIST
          value: $(params.INTERFACES)
      workspaces:
        - name: kubeconfigs
          workspace: pipeline-ws
    - name: send-ptp-report
      when:
        - input: "$(params.FEATURE)"
          operator: in
          values: ["ptp"]
      taskRef:
        name: send-to-gchat-space
        kind: Task
      runAfter:
        - run-ptp-suite
      params:
        - name: webhook-url
          value: $(params.NOTIF_URL)
        - name: message
          value: $(params.MESSAGE)
    - name: send-sriov-report
      when:
        - input: "$(params.FEATURE)"
          operator: in
          values: ["sriov"]
      taskRef:
        name: send-to-gchat-space
        kind: Task
      runAfter:
        - run-sriov-suite
      params:
        - name: webhook-url
          value: $(params.NOTIF_URL)
        - name: message
          value: $(params.MESSAGE)
  workspaces:
    - description: Shared data in this pipeline
      name: pipeline-ws
